# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: smart-vacc-fhir-bundle-gc1.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='smart-vacc-fhir-bundle-gc1.proto',
  package='smart_vacc_fhir_bundle',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n smart-vacc-fhir-bundle-gc1.proto\x12\x16smart_vacc_fhir_bundle\"\xc2\x04\n\x0eSmartVaccCert1\x12;\n\x05\x65ntry\x18\x01 \x03(\x0b\x32,.smart_vacc_fhir_bundle.SmartVaccCert1.Entry\x1a\xf2\x03\n\x05\x45ntry\x12G\n\x08resource\x18\x01 \x01(\x0b\x32\x35.smart_vacc_fhir_bundle.SmartVaccCert1.Entry.Resource\x1a\x9f\x03\n\x08Resource\x12\x14\n\x0cresourceType\x18\x02 \x01(\t\x12H\n\x04name\x18\x03 \x01(\x0b\x32:.smart_vacc_fhir_bundle.SmartVaccCert1.Entry.Resource.Name\x12W\n\x0cvaccine_code\x18\x04 \x01(\x0b\x32\x41.smart_vacc_fhir_bundle.SmartVaccCert1.Entry.Resource.vaccineCode\x1a%\n\x04Name\x12\x0e\n\x06\x66\x61mily\x18\x01 \x01(\t\x12\r\n\x05given\x18\x02 \x03(\t\x1a&\n\x06\x63oding\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0e\n\x06system\x18\x02 \x01(\t\x1aj\n\x0bvaccineCode\x12M\n\x07_coding\x18\x01 \x01(\x0b\x32<.smart_vacc_fhir_bundle.SmartVaccCert1.Entry.Resource.coding\x12\x0c\n\x04text\x18\x02 \x01(\t\x1a\x1f\n\x0cmanufacturer\x12\x0f\n\x07\x64isplay\x18\x01 \x01(\t'
)




_SMARTVACCCERT1_ENTRY_RESOURCE_NAME = _descriptor.Descriptor(
  name='Name',
  full_name='smart_vacc_fhir_bundle.SmartVaccCert1.Entry.Resource.Name',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='family', full_name='smart_vacc_fhir_bundle.SmartVaccCert1.Entry.Resource.Name.family', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='given', full_name='smart_vacc_fhir_bundle.SmartVaccCert1.Entry.Resource.Name.given', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=421,
  serialized_end=458,
)

_SMARTVACCCERT1_ENTRY_RESOURCE_CODING = _descriptor.Descriptor(
  name='coding',
  full_name='smart_vacc_fhir_bundle.SmartVaccCert1.Entry.Resource.coding',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='smart_vacc_fhir_bundle.SmartVaccCert1.Entry.Resource.coding.code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='system', full_name='smart_vacc_fhir_bundle.SmartVaccCert1.Entry.Resource.coding.system', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=460,
  serialized_end=498,
)

_SMARTVACCCERT1_ENTRY_RESOURCE_VACCINECODE = _descriptor.Descriptor(
  name='vaccineCode',
  full_name='smart_vacc_fhir_bundle.SmartVaccCert1.Entry.Resource.vaccineCode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='_coding', full_name='smart_vacc_fhir_bundle.SmartVaccCert1.Entry.Resource.vaccineCode._coding', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='text', full_name='smart_vacc_fhir_bundle.SmartVaccCert1.Entry.Resource.vaccineCode.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=500,
  serialized_end=606,
)

_SMARTVACCCERT1_ENTRY_RESOURCE_MANUFACTURER = _descriptor.Descriptor(
  name='manufacturer',
  full_name='smart_vacc_fhir_bundle.SmartVaccCert1.Entry.Resource.manufacturer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='display', full_name='smart_vacc_fhir_bundle.SmartVaccCert1.Entry.Resource.manufacturer.display', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=608,
  serialized_end=639,
)

_SMARTVACCCERT1_ENTRY_RESOURCE = _descriptor.Descriptor(
  name='Resource',
  full_name='smart_vacc_fhir_bundle.SmartVaccCert1.Entry.Resource',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='resourceType', full_name='smart_vacc_fhir_bundle.SmartVaccCert1.Entry.Resource.resourceType', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='smart_vacc_fhir_bundle.SmartVaccCert1.Entry.Resource.name', index=1,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vaccine_code', full_name='smart_vacc_fhir_bundle.SmartVaccCert1.Entry.Resource.vaccine_code', index=2,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_SMARTVACCCERT1_ENTRY_RESOURCE_NAME, _SMARTVACCCERT1_ENTRY_RESOURCE_CODING, _SMARTVACCCERT1_ENTRY_RESOURCE_VACCINECODE, _SMARTVACCCERT1_ENTRY_RESOURCE_MANUFACTURER, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=224,
  serialized_end=639,
)

_SMARTVACCCERT1_ENTRY = _descriptor.Descriptor(
  name='Entry',
  full_name='smart_vacc_fhir_bundle.SmartVaccCert1.Entry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='resource', full_name='smart_vacc_fhir_bundle.SmartVaccCert1.Entry.resource', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_SMARTVACCCERT1_ENTRY_RESOURCE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=639,
)

_SMARTVACCCERT1 = _descriptor.Descriptor(
  name='SmartVaccCert1',
  full_name='smart_vacc_fhir_bundle.SmartVaccCert1',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='entry', full_name='smart_vacc_fhir_bundle.SmartVaccCert1.entry', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_SMARTVACCCERT1_ENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=639,
)

_SMARTVACCCERT1_ENTRY_RESOURCE_NAME.containing_type = _SMARTVACCCERT1_ENTRY_RESOURCE
_SMARTVACCCERT1_ENTRY_RESOURCE_CODING.containing_type = _SMARTVACCCERT1_ENTRY_RESOURCE
_SMARTVACCCERT1_ENTRY_RESOURCE_VACCINECODE.fields_by_name['_coding'].message_type = _SMARTVACCCERT1_ENTRY_RESOURCE_CODING
_SMARTVACCCERT1_ENTRY_RESOURCE_VACCINECODE.containing_type = _SMARTVACCCERT1_ENTRY_RESOURCE
_SMARTVACCCERT1_ENTRY_RESOURCE_MANUFACTURER.containing_type = _SMARTVACCCERT1_ENTRY_RESOURCE
_SMARTVACCCERT1_ENTRY_RESOURCE.fields_by_name['name'].message_type = _SMARTVACCCERT1_ENTRY_RESOURCE_NAME
_SMARTVACCCERT1_ENTRY_RESOURCE.fields_by_name['vaccine_code'].message_type = _SMARTVACCCERT1_ENTRY_RESOURCE_VACCINECODE
_SMARTVACCCERT1_ENTRY_RESOURCE.containing_type = _SMARTVACCCERT1_ENTRY
_SMARTVACCCERT1_ENTRY.fields_by_name['resource'].message_type = _SMARTVACCCERT1_ENTRY_RESOURCE
_SMARTVACCCERT1_ENTRY.containing_type = _SMARTVACCCERT1
_SMARTVACCCERT1.fields_by_name['entry'].message_type = _SMARTVACCCERT1_ENTRY
DESCRIPTOR.message_types_by_name['SmartVaccCert1'] = _SMARTVACCCERT1
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SmartVaccCert1 = _reflection.GeneratedProtocolMessageType('SmartVaccCert1', (_message.Message,), {

  'Entry' : _reflection.GeneratedProtocolMessageType('Entry', (_message.Message,), {

    'Resource' : _reflection.GeneratedProtocolMessageType('Resource', (_message.Message,), {

      'Name' : _reflection.GeneratedProtocolMessageType('Name', (_message.Message,), {
        'DESCRIPTOR' : _SMARTVACCCERT1_ENTRY_RESOURCE_NAME,
        '__module__' : 'smart_vacc_fhir_bundle_gc1_pb2'
        # @@protoc_insertion_point(class_scope:smart_vacc_fhir_bundle.SmartVaccCert1.Entry.Resource.Name)
        })
      ,

      'coding' : _reflection.GeneratedProtocolMessageType('coding', (_message.Message,), {
        'DESCRIPTOR' : _SMARTVACCCERT1_ENTRY_RESOURCE_CODING,
        '__module__' : 'smart_vacc_fhir_bundle_gc1_pb2'
        # @@protoc_insertion_point(class_scope:smart_vacc_fhir_bundle.SmartVaccCert1.Entry.Resource.coding)
        })
      ,

      'vaccineCode' : _reflection.GeneratedProtocolMessageType('vaccineCode', (_message.Message,), {
        'DESCRIPTOR' : _SMARTVACCCERT1_ENTRY_RESOURCE_VACCINECODE,
        '__module__' : 'smart_vacc_fhir_bundle_gc1_pb2'
        # @@protoc_insertion_point(class_scope:smart_vacc_fhir_bundle.SmartVaccCert1.Entry.Resource.vaccineCode)
        })
      ,

      'manufacturer' : _reflection.GeneratedProtocolMessageType('manufacturer', (_message.Message,), {
        'DESCRIPTOR' : _SMARTVACCCERT1_ENTRY_RESOURCE_MANUFACTURER,
        '__module__' : 'smart_vacc_fhir_bundle_gc1_pb2'
        # @@protoc_insertion_point(class_scope:smart_vacc_fhir_bundle.SmartVaccCert1.Entry.Resource.manufacturer)
        })
      ,
      'DESCRIPTOR' : _SMARTVACCCERT1_ENTRY_RESOURCE,
      '__module__' : 'smart_vacc_fhir_bundle_gc1_pb2'
      # @@protoc_insertion_point(class_scope:smart_vacc_fhir_bundle.SmartVaccCert1.Entry.Resource)
      })
    ,
    'DESCRIPTOR' : _SMARTVACCCERT1_ENTRY,
    '__module__' : 'smart_vacc_fhir_bundle_gc1_pb2'
    # @@protoc_insertion_point(class_scope:smart_vacc_fhir_bundle.SmartVaccCert1.Entry)
    })
  ,
  'DESCRIPTOR' : _SMARTVACCCERT1,
  '__module__' : 'smart_vacc_fhir_bundle_gc1_pb2'
  # @@protoc_insertion_point(class_scope:smart_vacc_fhir_bundle.SmartVaccCert1)
  })
_sym_db.RegisterMessage(SmartVaccCert1)
_sym_db.RegisterMessage(SmartVaccCert1.Entry)
_sym_db.RegisterMessage(SmartVaccCert1.Entry.Resource)
_sym_db.RegisterMessage(SmartVaccCert1.Entry.Resource.Name)
_sym_db.RegisterMessage(SmartVaccCert1.Entry.Resource.coding)
_sym_db.RegisterMessage(SmartVaccCert1.Entry.Resource.vaccineCode)
_sym_db.RegisterMessage(SmartVaccCert1.Entry.Resource.manufacturer)


# @@protoc_insertion_point(module_scope)
