# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: smart-vacc-fhir-bundle-gc2.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='smart-vacc-fhir-bundle-gc2.proto',
  package='smart_vacc_fhir_bundle',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n smart-vacc-fhir-bundle-gc2.proto\x12\x16smart_vacc_fhir_bundle\"\xd8\x02\n\x0eSmartVaccCert2\x12;\n\x05\x65ntry\x18\x01 \x03(\x0b\x32,.smart_vacc_fhir_bundle.SmartVaccCert2.Entry\x1a\x88\x02\n\x05\x45ntry\x12G\n\x08resource\x18\x01 \x01(\x0b\x32\x35.smart_vacc_fhir_bundle.SmartVaccCert2.Entry.Resource\x1a\xb5\x01\n\x08Resource\x12Y\n\r_manufacturer\x18\x02 \x01(\x0b\x32\x42.smart_vacc_fhir_bundle.SmartVaccCert2.Entry.Resource.manufacturer\x12\x11\n\tlotNumber\x18\x03 \x01(\t\x12\x1a\n\x12occurrenceDateTime\x18\x04 \x01(\t\x1a\x1f\n\x0cmanufacturer\x12\x0f\n\x07\x64isplay\x18\x01 \x01(\t'
)




_SMARTVACCCERT2_ENTRY_RESOURCE_MANUFACTURER = _descriptor.Descriptor(
  name='manufacturer',
  full_name='smart_vacc_fhir_bundle.SmartVaccCert2.Entry.Resource.manufacturer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='display', full_name='smart_vacc_fhir_bundle.SmartVaccCert2.Entry.Resource.manufacturer.display', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=374,
  serialized_end=405,
)

_SMARTVACCCERT2_ENTRY_RESOURCE = _descriptor.Descriptor(
  name='Resource',
  full_name='smart_vacc_fhir_bundle.SmartVaccCert2.Entry.Resource',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='_manufacturer', full_name='smart_vacc_fhir_bundle.SmartVaccCert2.Entry.Resource._manufacturer', index=0,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lotNumber', full_name='smart_vacc_fhir_bundle.SmartVaccCert2.Entry.Resource.lotNumber', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='occurrenceDateTime', full_name='smart_vacc_fhir_bundle.SmartVaccCert2.Entry.Resource.occurrenceDateTime', index=2,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_SMARTVACCCERT2_ENTRY_RESOURCE_MANUFACTURER, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=224,
  serialized_end=405,
)

_SMARTVACCCERT2_ENTRY = _descriptor.Descriptor(
  name='Entry',
  full_name='smart_vacc_fhir_bundle.SmartVaccCert2.Entry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='resource', full_name='smart_vacc_fhir_bundle.SmartVaccCert2.Entry.resource', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_SMARTVACCCERT2_ENTRY_RESOURCE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=405,
)

_SMARTVACCCERT2 = _descriptor.Descriptor(
  name='SmartVaccCert2',
  full_name='smart_vacc_fhir_bundle.SmartVaccCert2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='entry', full_name='smart_vacc_fhir_bundle.SmartVaccCert2.entry', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_SMARTVACCCERT2_ENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=405,
)

_SMARTVACCCERT2_ENTRY_RESOURCE_MANUFACTURER.containing_type = _SMARTVACCCERT2_ENTRY_RESOURCE
_SMARTVACCCERT2_ENTRY_RESOURCE.fields_by_name['_manufacturer'].message_type = _SMARTVACCCERT2_ENTRY_RESOURCE_MANUFACTURER
_SMARTVACCCERT2_ENTRY_RESOURCE.containing_type = _SMARTVACCCERT2_ENTRY
_SMARTVACCCERT2_ENTRY.fields_by_name['resource'].message_type = _SMARTVACCCERT2_ENTRY_RESOURCE
_SMARTVACCCERT2_ENTRY.containing_type = _SMARTVACCCERT2
_SMARTVACCCERT2.fields_by_name['entry'].message_type = _SMARTVACCCERT2_ENTRY
DESCRIPTOR.message_types_by_name['SmartVaccCert2'] = _SMARTVACCCERT2
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SmartVaccCert2 = _reflection.GeneratedProtocolMessageType('SmartVaccCert2', (_message.Message,), {

  'Entry' : _reflection.GeneratedProtocolMessageType('Entry', (_message.Message,), {

    'Resource' : _reflection.GeneratedProtocolMessageType('Resource', (_message.Message,), {

      'manufacturer' : _reflection.GeneratedProtocolMessageType('manufacturer', (_message.Message,), {
        'DESCRIPTOR' : _SMARTVACCCERT2_ENTRY_RESOURCE_MANUFACTURER,
        '__module__' : 'smart_vacc_fhir_bundle_gc2_pb2'
        # @@protoc_insertion_point(class_scope:smart_vacc_fhir_bundle.SmartVaccCert2.Entry.Resource.manufacturer)
        })
      ,
      'DESCRIPTOR' : _SMARTVACCCERT2_ENTRY_RESOURCE,
      '__module__' : 'smart_vacc_fhir_bundle_gc2_pb2'
      # @@protoc_insertion_point(class_scope:smart_vacc_fhir_bundle.SmartVaccCert2.Entry.Resource)
      })
    ,
    'DESCRIPTOR' : _SMARTVACCCERT2_ENTRY,
    '__module__' : 'smart_vacc_fhir_bundle_gc2_pb2'
    # @@protoc_insertion_point(class_scope:smart_vacc_fhir_bundle.SmartVaccCert2.Entry)
    })
  ,
  'DESCRIPTOR' : _SMARTVACCCERT2,
  '__module__' : 'smart_vacc_fhir_bundle_gc2_pb2'
  # @@protoc_insertion_point(class_scope:smart_vacc_fhir_bundle.SmartVaccCert2)
  })
_sym_db.RegisterMessage(SmartVaccCert2)
_sym_db.RegisterMessage(SmartVaccCert2.Entry)
_sym_db.RegisterMessage(SmartVaccCert2.Entry.Resource)
_sym_db.RegisterMessage(SmartVaccCert2.Entry.Resource.manufacturer)


# @@protoc_insertion_point(module_scope)
