# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: smart-vacc-fhir-bundle-gc0.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='smart-vacc-fhir-bundle-gc0.proto',
  package='smart_vacc_fhir_bundle',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n smart-vacc-fhir-bundle-gc0.proto\x12\x16smart_vacc_fhir_bundle\"\xc4\x02\n\x0eSmartVaccCert0\x12;\n\x05\x65ntry\x18\x01 \x03(\x0b\x32,.smart_vacc_fhir_bundle.SmartVaccCert0.Entry\x1a\xf4\x01\n\x05\x45ntry\x12G\n\x08resource\x18\x01 \x01(\x0b\x32\x35.smart_vacc_fhir_bundle.SmartVaccCert0.Entry.Resource\x1a\xa1\x01\n\x08Resource\x12\x14\n\x0cresourceType\x18\x02 \x01(\t\x12H\n\x04name\x18\x03 \x01(\x0b\x32:.smart_vacc_fhir_bundle.SmartVaccCert0.Entry.Resource.Name\x12\x0e\n\x06status\x18\x04 \x01(\t\x1a%\n\x04Name\x12\x0e\n\x06\x66\x61mily\x18\x01 \x01(\t\x12\r\n\x05given\x18\x02 \x03(\t'
)




_SMARTVACCCERT0_ENTRY_RESOURCE_NAME = _descriptor.Descriptor(
  name='Name',
  full_name='smart_vacc_fhir_bundle.SmartVaccCert0.Entry.Resource.Name',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='family', full_name='smart_vacc_fhir_bundle.SmartVaccCert0.Entry.Resource.Name.family', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='given', full_name='smart_vacc_fhir_bundle.SmartVaccCert0.Entry.Resource.Name.given', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=348,
  serialized_end=385,
)

_SMARTVACCCERT0_ENTRY_RESOURCE = _descriptor.Descriptor(
  name='Resource',
  full_name='smart_vacc_fhir_bundle.SmartVaccCert0.Entry.Resource',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='resourceType', full_name='smart_vacc_fhir_bundle.SmartVaccCert0.Entry.Resource.resourceType', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='smart_vacc_fhir_bundle.SmartVaccCert0.Entry.Resource.name', index=1,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='smart_vacc_fhir_bundle.SmartVaccCert0.Entry.Resource.status', index=2,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_SMARTVACCCERT0_ENTRY_RESOURCE_NAME, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=224,
  serialized_end=385,
)

_SMARTVACCCERT0_ENTRY = _descriptor.Descriptor(
  name='Entry',
  full_name='smart_vacc_fhir_bundle.SmartVaccCert0.Entry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='resource', full_name='smart_vacc_fhir_bundle.SmartVaccCert0.Entry.resource', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_SMARTVACCCERT0_ENTRY_RESOURCE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=385,
)

_SMARTVACCCERT0 = _descriptor.Descriptor(
  name='SmartVaccCert0',
  full_name='smart_vacc_fhir_bundle.SmartVaccCert0',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='entry', full_name='smart_vacc_fhir_bundle.SmartVaccCert0.entry', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_SMARTVACCCERT0_ENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=385,
)

_SMARTVACCCERT0_ENTRY_RESOURCE_NAME.containing_type = _SMARTVACCCERT0_ENTRY_RESOURCE
_SMARTVACCCERT0_ENTRY_RESOURCE.fields_by_name['name'].message_type = _SMARTVACCCERT0_ENTRY_RESOURCE_NAME
_SMARTVACCCERT0_ENTRY_RESOURCE.containing_type = _SMARTVACCCERT0_ENTRY
_SMARTVACCCERT0_ENTRY.fields_by_name['resource'].message_type = _SMARTVACCCERT0_ENTRY_RESOURCE
_SMARTVACCCERT0_ENTRY.containing_type = _SMARTVACCCERT0
_SMARTVACCCERT0.fields_by_name['entry'].message_type = _SMARTVACCCERT0_ENTRY
DESCRIPTOR.message_types_by_name['SmartVaccCert0'] = _SMARTVACCCERT0
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SmartVaccCert0 = _reflection.GeneratedProtocolMessageType('SmartVaccCert0', (_message.Message,), {

  'Entry' : _reflection.GeneratedProtocolMessageType('Entry', (_message.Message,), {

    'Resource' : _reflection.GeneratedProtocolMessageType('Resource', (_message.Message,), {

      'Name' : _reflection.GeneratedProtocolMessageType('Name', (_message.Message,), {
        'DESCRIPTOR' : _SMARTVACCCERT0_ENTRY_RESOURCE_NAME,
        '__module__' : 'smart_vacc_fhir_bundle_gc0_pb2'
        # @@protoc_insertion_point(class_scope:smart_vacc_fhir_bundle.SmartVaccCert0.Entry.Resource.Name)
        })
      ,
      'DESCRIPTOR' : _SMARTVACCCERT0_ENTRY_RESOURCE,
      '__module__' : 'smart_vacc_fhir_bundle_gc0_pb2'
      # @@protoc_insertion_point(class_scope:smart_vacc_fhir_bundle.SmartVaccCert0.Entry.Resource)
      })
    ,
    'DESCRIPTOR' : _SMARTVACCCERT0_ENTRY,
    '__module__' : 'smart_vacc_fhir_bundle_gc0_pb2'
    # @@protoc_insertion_point(class_scope:smart_vacc_fhir_bundle.SmartVaccCert0.Entry)
    })
  ,
  'DESCRIPTOR' : _SMARTVACCCERT0,
  '__module__' : 'smart_vacc_fhir_bundle_gc0_pb2'
  # @@protoc_insertion_point(class_scope:smart_vacc_fhir_bundle.SmartVaccCert0)
  })
_sym_db.RegisterMessage(SmartVaccCert0)
_sym_db.RegisterMessage(SmartVaccCert0.Entry)
_sym_db.RegisterMessage(SmartVaccCert0.Entry.Resource)
_sym_db.RegisterMessage(SmartVaccCert0.Entry.Resource.Name)


# @@protoc_insertion_point(module_scope)
